// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BudgetCC.Infrastructure;

#nullable disable

namespace BudgetCC.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260907000359_InitialFinance")]
    partial class InitialFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BudgetCC.Infrastructure.AccountRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreditLimitCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Liquid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalAdjustmentCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedBalanceCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpcomingPaymentCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Liquid", "Type != 'credit' OR Liquid = 0");

                            t.HasCheckConstraint("CK_Account_Mask", "length(LastFour) = 4 AND LastFour NOT GLOB '*[^0-9]*'");

                            t.HasCheckConstraint("CK_Account_Sync", "SyncState IN ('nominal','syncing','attention')");

                            t.HasCheckConstraint("CK_Account_Type", "Type IN ('checking','savings','credit')");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.AllocationRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId", "Id");

                    b.ToTable("Allocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Allocation_Money", "AmountCents >= 0");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.EntryRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludedInForecast")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrimaryPaycheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasFilter("PrimaryPaycheck = 1 AND Archived = 0");

                    b.HasIndex("WorkspaceId", "AccountId");

                    b.ToTable("Entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entry_Frequency", "Frequency IS NULL OR Frequency IN ('weekly','biweekly','semimonthly','monthly','quarterly','annual','custom')");

                            t.HasCheckConstraint("CK_Entry_Interval", "Frequency != 'custom' OR (IntervalDays IS NOT NULL AND IntervalDays > 0)");

                            t.HasCheckConstraint("CK_Entry_Kind", "Kind IN ('income','expense')");

                            t.HasCheckConstraint("CK_Entry_Money", "AmountCents > 0");

                            t.HasCheckConstraint("CK_Entry_Paycheck", "PrimaryPaycheck = 0 OR Kind = 'income'");

                            t.HasCheckConstraint("CK_Entry_Source", "Source IN ('manual','synced','projected')");

                            t.HasCheckConstraint("CK_Entry_Variability", "Variability IN ('static','dynamic')");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.MembershipRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId", "Subject");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.OccurrenceRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkspaceId", "EntryId", "Date");

                    b.ToTable("Occurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_Occurrence_State", "(State = 'completed' AND CompletedAt IS NOT NULL) OR (State = 'skipped' AND CompletedAt IS NULL)");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.ReservationRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "AccountId");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Money", "AmountCents > 0");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.WorkspaceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ambient")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DailyPlanCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReserveCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SinkingFundCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", null, t =>
                        {
                            t.HasCheckConstraint("CK_Settings_NonNegative", "ReserveCents >= 0 AND SinkingFundCents >= 0 AND DailyPlanCents >= 0");
                        });
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.AccountRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.AllocationRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.EntryRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetCC.Infrastructure.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.MembershipRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.OccurrenceRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetCC.Infrastructure.EntryRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetCC.Infrastructure.ReservationRecord", b =>
                {
                    b.HasOne("BudgetCC.Infrastructure.WorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetCC.Infrastructure.AccountRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
